### ISSUE TITLE
testing & documentation

### ISSUE THREAD

**Issue by smerth** [mccrodp/entityreference_prepopulate#1]
Hi there, not sure if you want feed-back here or on Drupal.org?

I tried to install the module to see how it works, I can't follow your instructions so I thought I would send some notes in case it's helpful.

Here is your readme with me comments...

**D8 version under development (non functional)**
# Description

Allows the contents of an "Entity Reference" field to be pre-populated by
taking a parameter from the URL path.
# Install
1. Download and enable the module. 

> well that seems to work ok, at least it shows as 
1. Visit admin/structure/types/manage/[ENTITY-TYPE]/fields/[FIELD-NAME]
2. Enable "Entity reference prepopulate" under the instance settings.

> I guess this means to create an entity reference field and then under the edit tab for that field find "Entity reference prepopulate" and enable it... I can't find anything related to "Entity reference prepopulate" either on the "edit" tab for the entity reference field I created or on the "field settings" tab.

Needless to say I can't find any of the config fields you mention in the configuration instructions...

It looks like its early days for this module... so i hope this helps.  I am glad to test it as it develops

Cheers

**Comment by mccrodp** [comment]
Hey. Yea porting this hasn't even begun for D8 yet. Please see: https://www.drupal.org/node/2615320 for the porting issue on D.O. and this issue for information on the current blocking issue that needs some thought before dev even starts: https://www.drupal.org/node/1803064#comment-10717088

I reckon follow those issues on drupal.org and then test anything that gets developed in the coming while. Nothing to test for now though.

**Comment by smerth** [comment]
Oh, i started on d.o and ended up on github. thanks for pointing me to the right things to track. I'll watch those nodes.   Cheers!
